# .properties 계층구조 중복 발생
#yml, yaml을 통해 들여쓰기 계층구조 사용

## port 번호 변경 (default 8080)
#server:
#  port: 8081

spring:
  mvc:
    pathmatch:
#      Springboot2.4 이상에서는 기본적으로 pathPatterParser를 사용하고 있는데,
#      springfox와 같은 일부 라이브러리에서는 해당 pathPartern rule과 충돌나는 경우 path 방식 변경
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/basic
    username: root
    password: 1234
  jpa:
#    mariadb를 사용하지만 mysql에 핵심적인 기능이 다 들어있기 때문에 사용.
    database: mysql
#    innoDB 사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
#    테이블은 생성해주나, 스키마는 반드시 사전에 생성 필요
    generate-ddl: true
#    jpa는 인터페이스이고, hibernate 구현체(실질적 기능 구현)
    hibernate:
#      create 옵션은 매번 table을 drop후 재생성
#      update 옵션은 변경 사항만 alter를 적용하고 기존의 데이터 유지
#      변경 사항 중에 주로 추가 사항만 반영하고 삭제, 길이 변경 등 수정 사항은 적용 안되는 경우가 있음.
#      validate는 실제 DB와의 차이만을 check(컴파일 에러 발생시킴)
      ddl-auto: update
#      콘솔창에 ddl, dml문을 출력하여 보여주는 옵션
    show_sql: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
